name: Build IronRDP GUI Client

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build ironrdp-client-glutin
        run: |
          cd D:\a\IronRDP\IronRDP
          cargo build -p ironrdp-client-glutin --release

      - name: Install 7-Zip
        run: |
          choco install 7zip -y
        shell: powershell

      - name: Compress target directory using 7-Zip
        run: |
          & "C:\Program Files\7-Zip\7z.exe" a -tzip D:\a\IronRDP\IronRDP\target.zip D:\a\IronRDP\IronRDP\target\*
        shell: powershell

      - name: Upload target directory zip
        uses: actions/upload-artifact@v4
        with:
          name: ironrdp-target-archive
          path: D:\a\IronRDP\IronRDP\target.zip
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: true
