name: Build IronRDP Client

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest  # 使用 macOS runner 编译 macOS 应用

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build ironrdp-client
        run: |
          cd crates/ironrdp-client
          cargo build --release

      - name: List IronRDP workspace contents
        run: |
          echo "=== Build output files in /Users/runner/work/IronRDP/IronRDP ==="
          ls -alh /Users/runner/work/IronRDP/IronRDP

      - name: Compress IronRDP build output
        run: |
          cd /Users/runner/work/IronRDP
          zip -r ironrdp-client-build.zip IronRDP

      - name: Upload full IronRDP directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ironrdp-client-full-archive
          path: /Users/runner/work/IronRDP/ironrdp-client-build.zip
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: true
