name: Build IronRDP Client

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest  # 使用 macOS runner 以编译 macOS 应用

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build ironrdp-client
        run: |
          cd crates/ironrdp-client
          cargo build --release
          echo "=== Build output files in target/release ==="
          ls -l target/release/

      - name: Bundle as macOS .app
        run: |
          cd crates/ironrdp-client
          APP_NAME="ironrdp-client"
          APP_DIR="${APP_NAME}.app"
          mkdir -p "${APP_DIR}/Contents/MacOS"
          cp "target/release/${APP_NAME}" "${APP_DIR}/Contents/MacOS/${APP_NAME}"
          # 创建 Info.plist 文件
          cat > "${APP_DIR}/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>
  <string>${APP_NAME}</string>
  <key>CFBundleDisplayName</key>
  <string>${APP_NAME}</string>
  <key>CFBundleIdentifier</key>
  <string>com.example.${APP_NAME}</string>
  <key>CFBundleVersion</key>
  <string>0.1.0</string>
  <key>CFBundleExecutable</key>
  <string>${APP_NAME}</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
</dict>
</plist>
EOF
          echo "=== .app bundle structure ==="
          find "${APP_DIR}"

      - name: Upload ironrdp-client.app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ironrdp-client-macos-app
          path: crates/ironrdp-client/ironrdp-client.app
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: true
