name: Build IronRDP Client macOS App

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build ironrdp-client .app bundle
        run: |
          cd crates/ironrdp-client
          cargo build --release
          echo "=== Contents of target/release ==="
          ls -alh target/release
          echo "=== Contents of target/release/bundle/osx ==="
          ls -alh target/release/bundle/osx
          echo "=== Contents of /Users/runner/work/IronRDP/IronRDP ==="
          ls -alh /Users/runner/work/IronRDP/IronRDP

      - name: Upload ironrdp-client .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: ironrdp-client-macos-app
          path: crates/ironrdp-client/target/release/bundle/osx/ironrdp-client.app
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: true
        env:
          CARGO_TERM_COLOR: always
